// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: news/v1/news.proto

package newsv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on NewsServiceGetRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *NewsServiceGetRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on NewsServiceGetRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// NewsServiceGetRequestMultiError, or nil if none found.
func (m *NewsServiceGetRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *NewsServiceGetRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return NewsServiceGetRequestMultiError(errors)
	}

	return nil
}

// NewsServiceGetRequestMultiError is an error wrapping multiple validation
// errors returned by NewsServiceGetRequest.ValidateAll() if the designated
// constraints aren't met.
type NewsServiceGetRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NewsServiceGetRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NewsServiceGetRequestMultiError) AllErrors() []error { return m }

// NewsServiceGetRequestValidationError is the validation error returned by
// NewsServiceGetRequest.Validate if the designated constraints aren't met.
type NewsServiceGetRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NewsServiceGetRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NewsServiceGetRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NewsServiceGetRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NewsServiceGetRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NewsServiceGetRequestValidationError) ErrorName() string {
	return "NewsServiceGetRequestValidationError"
}

// Error satisfies the builtin error interface
func (e NewsServiceGetRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNewsServiceGetRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NewsServiceGetRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NewsServiceGetRequestValidationError{}

// Validate checks the field values on NewsServiceGetResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *NewsServiceGetResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on NewsServiceGetResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// NewsServiceGetResponseMultiError, or nil if none found.
func (m *NewsServiceGetResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *NewsServiceGetResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Author

	// no validation rules for Title

	// no validation rules for Summary

	// no validation rules for Content

	// no validation rules for Source

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, NewsServiceGetResponseValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, NewsServiceGetResponseValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return NewsServiceGetResponseValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, NewsServiceGetResponseValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, NewsServiceGetResponseValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return NewsServiceGetResponseValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetDeletedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, NewsServiceGetResponseValidationError{
					field:  "DeletedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, NewsServiceGetResponseValidationError{
					field:  "DeletedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDeletedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return NewsServiceGetResponseValidationError{
				field:  "DeletedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return NewsServiceGetResponseMultiError(errors)
	}

	return nil
}

// NewsServiceGetResponseMultiError is an error wrapping multiple validation
// errors returned by NewsServiceGetResponse.ValidateAll() if the designated
// constraints aren't met.
type NewsServiceGetResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NewsServiceGetResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NewsServiceGetResponseMultiError) AllErrors() []error { return m }

// NewsServiceGetResponseValidationError is the validation error returned by
// NewsServiceGetResponse.Validate if the designated constraints aren't met.
type NewsServiceGetResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NewsServiceGetResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NewsServiceGetResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NewsServiceGetResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NewsServiceGetResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NewsServiceGetResponseValidationError) ErrorName() string {
	return "NewsServiceGetResponseValidationError"
}

// Error satisfies the builtin error interface
func (e NewsServiceGetResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNewsServiceGetResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NewsServiceGetResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NewsServiceGetResponseValidationError{}

// Validate checks the field values on NewsServiceCreateRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *NewsServiceCreateRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on NewsServiceCreateRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// NewsServiceCreateRequestMultiError, or nil if none found.
func (m *NewsServiceCreateRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *NewsServiceCreateRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Author

	// no validation rules for Title

	// no validation rules for Summary

	// no validation rules for Content

	// no validation rules for Source

	if len(errors) > 0 {
		return NewsServiceCreateRequestMultiError(errors)
	}

	return nil
}

// NewsServiceCreateRequestMultiError is an error wrapping multiple validation
// errors returned by NewsServiceCreateRequest.ValidateAll() if the designated
// constraints aren't met.
type NewsServiceCreateRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NewsServiceCreateRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NewsServiceCreateRequestMultiError) AllErrors() []error { return m }

// NewsServiceCreateRequestValidationError is the validation error returned by
// NewsServiceCreateRequest.Validate if the designated constraints aren't met.
type NewsServiceCreateRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NewsServiceCreateRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NewsServiceCreateRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NewsServiceCreateRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NewsServiceCreateRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NewsServiceCreateRequestValidationError) ErrorName() string {
	return "NewsServiceCreateRequestValidationError"
}

// Error satisfies the builtin error interface
func (e NewsServiceCreateRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNewsServiceCreateRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NewsServiceCreateRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NewsServiceCreateRequestValidationError{}

// Validate checks the field values on NewsServiceCreateResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *NewsServiceCreateResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on NewsServiceCreateResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// NewsServiceCreateResponseMultiError, or nil if none found.
func (m *NewsServiceCreateResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *NewsServiceCreateResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Author

	// no validation rules for Title

	// no validation rules for Summary

	// no validation rules for Content

	// no validation rules for Source

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, NewsServiceCreateResponseValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, NewsServiceCreateResponseValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return NewsServiceCreateResponseValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, NewsServiceCreateResponseValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, NewsServiceCreateResponseValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return NewsServiceCreateResponseValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetDeletedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, NewsServiceCreateResponseValidationError{
					field:  "DeletedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, NewsServiceCreateResponseValidationError{
					field:  "DeletedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDeletedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return NewsServiceCreateResponseValidationError{
				field:  "DeletedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return NewsServiceCreateResponseMultiError(errors)
	}

	return nil
}

// NewsServiceCreateResponseMultiError is an error wrapping multiple validation
// errors returned by NewsServiceCreateResponse.ValidateAll() if the
// designated constraints aren't met.
type NewsServiceCreateResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NewsServiceCreateResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NewsServiceCreateResponseMultiError) AllErrors() []error { return m }

// NewsServiceCreateResponseValidationError is the validation error returned by
// NewsServiceCreateResponse.Validate if the designated constraints aren't met.
type NewsServiceCreateResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NewsServiceCreateResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NewsServiceCreateResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NewsServiceCreateResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NewsServiceCreateResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NewsServiceCreateResponseValidationError) ErrorName() string {
	return "NewsServiceCreateResponseValidationError"
}

// Error satisfies the builtin error interface
func (e NewsServiceCreateResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNewsServiceCreateResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NewsServiceCreateResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NewsServiceCreateResponseValidationError{}

// Validate checks the field values on NewsID with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *NewsID) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on NewsID with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in NewsIDMultiError, or nil if none found.
func (m *NewsID) ValidateAll() error {
	return m.validate(true)
}

func (m *NewsID) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return NewsIDMultiError(errors)
	}

	return nil
}

// NewsIDMultiError is an error wrapping multiple validation errors returned by
// NewsID.ValidateAll() if the designated constraints aren't met.
type NewsIDMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NewsIDMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NewsIDMultiError) AllErrors() []error { return m }

// NewsIDValidationError is the validation error returned by NewsID.Validate if
// the designated constraints aren't met.
type NewsIDValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NewsIDValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NewsIDValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NewsIDValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NewsIDValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NewsIDValidationError) ErrorName() string { return "NewsIDValidationError" }

// Error satisfies the builtin error interface
func (e NewsIDValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNewsID.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NewsIDValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NewsIDValidationError{}

// Validate checks the field values on NewsIdResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *NewsIdResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on NewsIdResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in NewsIdResponseMultiError,
// or nil if none found.
func (m *NewsIdResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *NewsIdResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if len(errors) > 0 {
		return NewsIdResponseMultiError(errors)
	}

	return nil
}

// NewsIdResponseMultiError is an error wrapping multiple validation errors
// returned by NewsIdResponse.ValidateAll() if the designated constraints
// aren't met.
type NewsIdResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m NewsIdResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m NewsIdResponseMultiError) AllErrors() []error { return m }

// NewsIdResponseValidationError is the validation error returned by
// NewsIdResponse.Validate if the designated constraints aren't met.
type NewsIdResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e NewsIdResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e NewsIdResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e NewsIdResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e NewsIdResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e NewsIdResponseValidationError) ErrorName() string { return "NewsIdResponseValidationError" }

// Error satisfies the builtin error interface
func (e NewsIdResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sNewsIdResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = NewsIdResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = NewsIdResponseValidationError{}
